회원가입 API
o-tao/todo-list pull request #20
Opened 2024-09-18 11:10 UTC by o-tao

- 수정사항
  - board → todo 네이밍 변경
  - README.md 회원가입 ResponseBody에서 password 응답 제거 → API 반영
 
- API
  - 회원 생성 API
  - 중복회원 생성 시 예외처리
  - 회원 생성 시 아이디, 비밀번호 미입력에 대한 예외처리 (Validation)

2024-09-18 12:58 UTC, cousim46 requested changes
회원가입 API 만드시느라 고생많으셨습니다!
해당 PR에 대해 코드리뷰 남겼습니다.
만약 이해가 안되는 부분이나 의아한 부분은 편하게 말씀해주시면 감사하겠습니다!
고생하셨습니다 :)

2024-09-18 12:58 UTC, cousim46 commented on src/main/java/com/app/todolist/api/members/dto/MemberRequest.java
> +@NoArgsConstructor
해당 객체는 컨트롤단에서 클라이언트에 요청값을 받기위한 객체로 보이네요!
롬복을 활용하여 값이 바인딩되게 설정해주셨는데 저는 주로 아래와 같이 사용합니다!

```java
@Getter
@AllArgsConstructor
```
또는

```java
@Setter
@NoArgsConstructor
```

해당 코드에서는 NoArgsConstructor을 지우셔도 될거 같습니다!

2024-09-18 12:58 UTC, cousim46 commented on src/main/java/com/app/todolist/domain/members/Member.java
> +}
Todo 객체에서는 @NoArgsConstructor + 인자가 있는 생성자를 사용하셨던데 여기에서는 사용을 안해서 통일성이 깨지는거 같습니다!
저는 Todo 객체에서 선언하신 방법을 선호합니다! 만약 해당 코드를 수정해본다면 아래와 같이 될거 같은데 이거는 상민님이 판단 후 더 적절한 방법을 사용하시는게 좋을거 같습니다!

```java
@Entity
@Getter
@Table(name = "members")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Member extends BaseEntity {

    @Column(nullable = false)
    private String email;

    @Column(nullable = false)
    private String password;

    private String role;

   private Member(String email, String password) {
        this.email = email;
        this.password = password;
    }

    public static Member create(String email, String password) {
        return new Member(email, password);
    }
}
```
@NoArgsConstructor(access = AccessLevel.PROTECTED) 간략하게 설명 드리자면 JPA에서는 리플렉션이라는것을 사용해서 값을 매핑해줍니다. 그런데 리프랙션을 하여 객체를 생성할때 기본생성자가 존재해야하는데 자바에서는 인자가 있는 생성자를 생성하면 기본 생성자를 생성안해줘서 해당 어노테이션을 사용하였습니다.
그리고 access 레벨을 설정해줬는데 private으로 설정하면 접근하지 못하여 Protected로 설정하였습니다!

2024-09-18 12:58 UTC, cousim46 commented on src/main/java/com/app/todolist/domain/members/Member.java
> +    private String role;
해당 권한값을 String 보다는 Enum을 활용해보시는게 어떨까요!
```java
@Getter
@RequiredArgsConstructor
public enum Role {
    USER("일반 사용자"), ADMIN("관리자");
   private final String type;
}
```

Member.java
```java
@Enumberated(EnumType.STRING)
private Role role;
```
이와 같이 Member 객체에 활용하면 좋을거 같습니다! 그리고 Enumberated 속성에는 Original, String이 존재하는데 Original로 하였을때 데이터베이스에는 Enum이 선언된 순서로 저장이 됩니다. 이때 Enum에 대한 값이 바뀌게 되면 좋지 못한 상황이 발생해서 저는 String으로 하는것을 지향합니다.

2024-09-18 12:58 UTC, cousim46 commented on src/main/java/com/app/todolist/api/members/MemberService.java
> +            throw new IllegalStateException("이미 존재하는 회원입니다.");
자바에서 기본적으로 제공해주는 예외를 활용하셨네요!
이와 같이하는 방법도 괜찮지만 커스텀하게 예외를 만들어서 처리해보시면 어떨까요!
그랬을때 상황에 맞는 상태 코드값과 메시지를 만들어서 활용할 수 있을거 같습니다!
```json
{
    "time" : "2024-09-18 21:46:50" // 발생시간
    "status" : "CONFILCT",
    "code" : 409,
    "message" : "이미 가입된 이메일이 존재합니다."
}
``` 
아래 블로그는 커스텀 익셉션을 만들어서 전역적으로 에러 처리를 하는 방법에 대해 작성되어있습니다! 만드실때 참고하시면 좋을거 같아서 공유드립니다.
https://hoestory.tistory.com/48

2024-09-18 12:58 UTC, cousim46 commented on src/main/resources/application.yml
> +      ddl-auto: create
ddl-auto를 create로 하고 PR을 올려주셨는데 해당 PR이 머지되고 다른 이슈를 작업하시려고 브랜치를 파고 빌드를 돌리게 되면 회원가입과 같은 작업을 처음부터 해야되는 상황이 발생할거 같습니다!
update로 수정해서 수정사항이 있을경우에만 DB에 반영되도록 하는게 어떨가요!

2024-09-18 12:58 UTC, cousim46 commented on src/test/java/com/app/todolist/api/members/MemberServiceTest.java
> +class MemberServiceTest {
회원가입에 대한 예외 케이스 테스트코드 정말 잘 작성해주셨네요!
예외 케이스 말고 성공케이스도 테스트코드로 있으면 좋을거 같습니다!

2024-09-18 12:58 UTC, cousim46 commented on src/test/java/com/app/todolist/domain/members/MemberRepositoryTest.java
> +        Assertions.assertThat(findMember.getCreatedAt().isAfter(now)).isTrue();
현재 `LocalDateTime now = LocalDateTime.now()`를 활용하셔서 검증하시고 계신데 DisplayName과 테스트코드가 일치하지 않은거 같습니다!
아래와 같이 수정해보시는게 어떨가요!
```java
 // given
        Member member = Member.create("tao@exemple.com", "1234");
        memberRepository.save(member);

        // when
        Member findMember = memberRepository.findAll().stream().findFirst().orElseThrow();

        // then
        Assertions.assertThat(findMember.getCreatedAt()).isNotNull();
```

2024-09-19 09:15 UTC, loadkrnis commented on src/main/java/com/app/todolist/domain/members/Member.java
> +    private String email;
email, password 둘 다 length 설정이 안되어있는데요. 
그럼 JPA에서 자동으로 varchar(255)로 설정됩니다.

```java
@Column(nullable = false, length = 50)
```
위 처럼 length를 지정해주어야 테이블 선언시 불필요한 varchar 사이즈로 선언하지 않을 것 같습니다.

2024-09-19 09:15 UTC, loadkrnis commented on src/main/java/com/app/todolist/domain/members/MemberRepository.java
> +    boolean existsByEmail(String email);
요거 테스트 코드가 없네용 ㅎㅎ

2024-09-19 09:15 UTC, loadkrnis commented on src/test/java/com/app/todolist/api/members/MemberServiceTest.java
> +        IllegalStateException e = assertThrows(IllegalStateException.class, () -> memberService.create(member2));
두번째 실행하는 create 메서드에서 예외가 발생하니 
29번 라인이 `when`절이 되어야할 것 같습니당

```java
        // given
        Member member1 = Member.create("tao@exemple.com", "1234");
        Member member2 = Member.create("tao@exemple.com", "1234");
        memberService.create(member1);

        // when
        IllegalStateException e = assertThrows(IllegalStateException.class, () -> memberService.create(member2));

        // then
        assertThat(e.getClass()).isEqualTo(IllegalStateException.class);
        assertThat(e.getMessage()).isEqualTo("이미 존재하는 회원입니다.");
```

2024-09-19 09:15 UTC, loadkrnis commented on src/test/java/com/app/todolist/domain/members/MemberRepositoryTest.java
> +@Import(AuditingConfig.class)
DataJpaTest 테스트 실행시 AuditConfig 파일이 빈으로 생성되지 않아서 붙여주신 것 같은데요.

이건 궁금해서 그런데 Member에서 AuditConfig가 꼭 필요한상황인가요?

2024-09-19 14:03 UTC, o-tao commented on src/main/java/com/app/todolist/api/members/dto/MemberRequest.java
> +@NoArgsConstructor
감사합니다

이 부분에서
AllArgsConstructor는 MemberController의 Valid에 대한 테스트코드를 짜던 중 Setter를 사용하지 않아 직접 값을 넣어 사용하지 못해 모든필드 값을 파라미터로 받는 생성자를 추가하기 위해 사용하였고
이후 직접 Request를 보내 회원 생성에 대한 PostMapping을 테스트 하던 중 Jackson의 객체 역직렬화 과정에서 오류가 발생해 기본생성자 추가를 위해 @NoArgsConstructor 어노테이션을 추가했습니다.

Entity를 사용할때 Setter의 사용을 지양하여 구현하던중 Request DTO에 대해서도 Setter 사용을 지양해야한다라는 생각에 고민하고 있던 상황이었는데 리뷰해주신 것을 토대로 학습하여 Entity와 DTO의 사용성에 대해 더욱 명확하게 구분되었습니다!

NoArgsConstructor를 지우면 역직렬화 과정에서 오류가 발생해
Setter와 NoArgsConstructor를 적용하고자 합니다.

한가지 질문이 있는데 현재 테스트 해본 결과 Setter만 추가하더라도 문제가 발생되지 않는데 NoArgsConstructor를 같이 추가하는 이유가 따로 있는걸까요??

2024-09-19 14:29 UTC, cousim46 commented on src/main/java/com/app/todolist/api/members/dto/MemberRequest.java
> +@NoArgsConstructor
저같은 경우는 인자가 있는 생성자를 생성할때도 있다 보니 기본 생성자를 생성해주는 롬복 어노테이션을 사용합니다! 인자가 있을 경우 기본생성자를 자동으로 생성을 안해줘서 사용합니다!

2024-09-19 14:30 UTC, cousim46 commented on src/main/java/com/app/todolist/api/members/dto/MemberRequest.java
> +@NoArgsConstructor
그리고 Setter을 지양하신다고 하셨는데 왜 그런지 설명도 같이 적어주시면 좋을거 같습니다 :)

2024-09-19 15:18 UTC, o-tao commented on src/main/java/com/app/todolist/api/members/dto/MemberRequest.java
> +@NoArgsConstructor
Entity의 경우 비즈니스 로직이 존재하고 실제 데이터가 변경되는데 그 과정에서 Setter를 사용하여 값을 설정할 경우 사용자의 의도파악, 일관성 유지, 유지보수 측면에서 불리할 수 있습니다.

ex)

```java
Member member = new Member();
member.setEmail("tao@exemple.com")
member.setPassword("1234")
```
Setter를 사용해 값을 설정 할 경우 위의 예시와 처럼 그 행위의 의도와 코드의 일관성을 해칠 수 있습니다.
또한 변경 포인트를 추적하기 어려워 유지보수 측면에서도 불리하게 작용합니다.

```java
public void changeInfo(String email, String password) {
    this.email = email;
    this.password = password;
}
```

```java
member.changeInfo("tao@exemple.com", "1234");
```
이와같이 Entity에 메서드를 생성하여 사용 할 경우 사용자의 의도를 명확히 구분할 수 있을 뿐만 아니라 객체의 일관성 또한 유지할 수 있고 변경 포인트를 추적하기 수월 해져 유지보수 측면에서도 더욱 유리합니다.

DTO의 경우 목적 자체에 어떠한 로직이 있다기보다 단순히 데이터 전달을 위해 쓰여 Getter, Setter를 자유롭게 사용해도 무방합니다.

2024-09-19 15:25 UTC, o-tao commented on src/main/java/com/app/todolist/api/members/dto/MemberRequest.java
> +@NoArgsConstructor
남겨주신 내용을 바탕으로 불필요한 어노테이션 제거하여 반영하였습니다! 감사합니다 :)

변경점
- MemberRequest 어노테이션 수정
```java
@Setter
@NoArgsConstructor
```

- 어노테이션 수정에 따른 MemberControllerTest 코드 수정

2024-09-21 14:46 UTC, o-tao commented on src/main/java/com/app/todolist/domain/members/Member.java
> +    private String role;
말씀해 주신 부분 테스트 도중 넣어 놓았던 컬럼이여서 제거 하였습니다 미처 확인하지 못하고 혼동 드린거 같아서 죄송합니다 ㅠㅠ

말씀해주신 Enum 사용 부분에 대해서는 Toto 상태값 기능 추가시 기억해놓고 있다가 적용하도록하겠습니다 감사합니다!

2024-09-21 17:45 UTC, o-tao commented on src/main/java/com/app/todolist/api/members/MemberService.java
> +            throw new IllegalStateException("이미 존재하는 회원입니다.");
말씀해 주신 부분 현재까지 적용된 예외처리에 대하여 반영하였습니다!

- 아이디 미입력에 대한 예외 Response
```json
{
    "time": "2024-09-22 02:43:34",
    "status": "BAD_REQUEST",
    "code": 400,
    "message": {
        "email": "이메일을 입력하세요."
    }
}
```

- 비밀번호 미입력에 대한 예외 Response
```json
{
    "time": "2024-09-22 02:41:54",
    "status": "BAD_REQUEST",
    "code": 400,
    "message": {
        "password": "비밀번호를 입력하세요."
    }
}
```

- 중복회원에 대한 예외 Response
```json
{
    "time": "2024-09-22 02:44:23",
    "status": "CONFLICT",
    "code": 409,
    "message": "이미 가입된 이메일이 존재합니다."
}
```

2024-09-21 17:58 UTC, o-tao commented on src/main/resources/application.yml
> +      ddl-auto: create
넵 말씀해주신것처럼 이후 API 구현시 반복적인 작업이 일어날 것 같아 해당내용 반영하였습니다.

2024-09-21 18:50 UTC, o-tao commented on src/main/java/com/app/todolist/api/members/MemberService.java
> +            throw new IllegalStateException("이미 존재하는 회원입니다.");
추가로 커스텀 예외처리에 따른 테스트코드 내용 수정하였습니다.

2024-09-21 18:54 UTC, o-tao commented on src/test/java/com/app/todolist/api/members/MemberServiceTest.java
> +class MemberServiceTest {
감사합니다 말씀해주신 내용 반영하였습니다! :)

2024-09-21 19:50 UTC, o-tao commented on src/test/java/com/app/todolist/domain/members/MemberRepositoryTest.java
> +        Assertions.assertThat(findMember.getCreatedAt().isAfter(now)).isTrue();
해당 테스트코드 작성 당시 시간을 테스트 한다는 생각에 값의 존재 유무보다 회원가입시 생성 시간이 현재 시간보다 과거인가를 체크했던거 같습니다.
리뷰해주신 내용 확인 후 다시보니 코드의 의미가 약간 추상적으로 보였던거 같아 수정하였습니다 감사합니다!

2024-09-21 20:04 UTC, o-tao commented on src/main/java/com/app/todolist/domain/members/Member.java
> +    private String email;
해당 내용 반영하였습니다 감사합니다!

2024-09-21 20:05 UTC, o-tao commented on src/test/java/com/app/todolist/api/members/MemberServiceTest.java
> +        IllegalStateException e = assertThrows(IllegalStateException.class, () -> memberService.create(member2));
해당내용 반영하였습니다 감사합니다!

2024-09-21 20:45 UTC, o-tao commented on src/main/java/com/app/todolist/domain/members/MemberRepository.java
> +    boolean existsByEmail(String email);
existsByEmail에 대한 테스트코드 작성하였습니다

2024-09-22 09:58 UTC, cousim46 reviewed
리뷰 내용 반영하시느라 정말 고생많으셨습니다!
리뷰 반영해주신 내용중에서 추가적으로 궁금한 내용이 있어서 리뷰 남기게되었습니다! 확인 후 의견달아주시면 감사하겠습니다!

2024-09-22 09:58 UTC, cousim46 commented on src/main/java/com/app/todolist/api/dto/TodoExceptionResponse.java
> +    private final T message;
현재 코드에서는 중복이라는 예외가 발생하게 되면 HttpStatus = Conflict, code = 409일것이고 메시지 내용만 달라지게 될거 같습니다. 
그럼 서버에서 내려주는 메시지를 사용자에게 그대로 노출시키는 방향으로 생각하고 계셔서 이와 같이 하신것일까요?? 
그게 아니라면 클라이언트가 인지할 수 있는 필드를 하나 더 추가하시는게 어떨까요?

2024-09-22 10:32 UTC, o-tao commented on src/main/java/com/app/todolist/api/dto/TodoExceptionResponse.java
> +    private final T message;
넵 저는 사용자에게 그대로 노출시키는 방향으로 생각했었습니다

회운님이 해주신 말씀이
```json
{
    "time": "2024-09-22 02:44:23",
    "status": "CONFLICT",
    "statusMessage": "DUPLICATED_MEMBER_ID",
    "code": 409,
    "message": "이미 가입된 이메일이 존재합니다."
}
```
이렇게 status에 대한 메세지를 추가하여 클라이언트가 응답을 받았을 때 어떤것에 해당하는 중복에러 인가에 대하여 더욱 명확성을 가지게 하는것으로 이해했는데 제가 이해한게 맞을까요??

2024-09-22 11:42 UTC, o-tao commented on src/main/java/com/app/todolist/api/dto/TodoExceptionResponse.java
> +    private final T message;
```json
{
    "code": 400,
    "message": "이메일은 필수"
}
```

2024-09-22 12:52 UTC, o-tao commented on src/main/java/com/app/todolist/domain/members/Member.java
> +}
해당 내용에서는 MemberRequest에서 toEntity화 하여 값을 Member객체에서 사용하는 방식이 개인적으로 조금 더 직관적으로 바라볼 수 있다고 판단하였습니다 좋은 리뷰내용 남겨주셔서 감사합니다

통일성에 대해서는 기억해서 Todo생성 API구현 시 반영하도록 하겠습니다!

2024-09-25 12:17 UTC, cousim46 approved these changes
고생하셨습니다! 머지하셔도 될거같습니다!

2024-09-26 05:50 UTC, o-tao commented on src/test/java/com/app/todolist/domain/members/MemberRepositoryTest.java
> +@Import(AuditingConfig.class)
현재 @EnableJpaAuditing 어노테이션을 활용하여 Auditing 기능을 사용하고 있어 BaseEntity에서 사용하는 생성, 수정시간을 @CreatedDate와 @LastModifiedDate 어노테이션을 사용하여 Entity 내에서 자동으로 관리하도록 설정해 놓았습니다.
해당 기능을 사용하기 위해서는 테스트 실행시에도 @EnableJpaAuditing가 추가되어있는 AuditingConfig클래스를 Import해서 사용해야 합니다.

민규님의 리뷰를 확인 후 재검토 해보았는데
저의 경우에 Auditing기능 중 생성, 수정시간만 자동생성 목적으로 사용하고 있었습니다.
생성, 수정시간만을 사용하기 위한 목적이라면
생성, 수정시간 관리 어노테이션을 @CreationTimestamp, @UpdateTimestamp으로 관리하는 편이 테스트시 추가적인 Import없이 사용할 수 있고 관리하는게 더욱 효율적일거 같아 생성, 수정시간부분 수정하고 Auditing기능을 제거 하였습니다.

Auditing에 추가적인 기능 활용시에 사용하고 생성, 수정시간만을 관리하기 위한 목적이라면 변경된 방법으로 사용하고자 합니다

```java
// as-is

// 테스트코드에 @Import(AuditingConfig.class) 선언
// AuditingConfig 클래스
@EnableJpaAuditing
@Configuration
public class AuditingConfig {
}

// BaseEntity
@Getter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public class BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @CreatedDate
    @Column(nullable = false, updatable = false, insertable = false)
    private LocalDateTime createdAt;
    @LastModifiedDate
    @Column(nullable = false, insertable = false)
    private LocalDateTime updatedAt;
}
```
---
```java
// to-be

// 테스트코드 @Import(AuditingConfig.class) 제거
// AuditingConfig 클래스 제거

// BaseEntity
@Getter
@MappedSuperclass
public class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
```

2024-09-27 05:32 UTC, merged