Todo 생성 API
o-tao/todo-list pull request #22
Opened 2024-09-29 10:19 UTC by o-tao

- Todo 생성 API
  - [POST] /api/todos
  - 생성 시 defalut 상태값 '할일'
#### RequestBody
```json
{
    "memberId": 1,
    "title": "todo title",
    "content": "todo content"
}
```

#### ResponseBody
```json
{
    "id": 1,
    "title": "todo title",
    "content": "todo content",
    "status": "할일",
    "createdAt": "2024-09-14 14:35:33",
    "updatedAt": "2024-09-14 14:35:33",
    "member": {
      "id": 1,
      "email": "tao@example.com"
    }
}
```

  - 제목을 입력하지 않을 경우에 대한 예외처리 (Custom Exception)
#### Request
```json
{
    "memberId": 1,
    "title": null,
    "content": "todo content"
}
```

#### Response
```json
{
    "code": 400,
    "message": "제목을 입력하세요."
}
```

  - 존재하지 않는 회원이 Todo를 생성 할 경우에 대한 예외처리 (Custom Exception)
#### Request
```json
{
    "memberId": 3,
    "title": "todo title",
    "content": "todo content"
}
```

#### Response
```json
{
    "code": 400,
    "message": "회원이 존재하지 않습니다."
}
```

2024-09-30 14:27 UTC, cousim46 requested changes
Todo 생성하는 API와 테스트코드 작성하시느라 정말 고생많으셨습니다!
수정했으면 하는 내용과 의미가 애매한 부분에 대해서 리뷰를 작성하였습니다!
궁금하신 내용이나 이해 안되는 내용이 있다면 편하게 코멘트 달아주세요 :)

2024-09-30 14:27 UTC, cousim46 commented on src/main/java/com/app/todolist/api/todos/dto/TodoRequest.java
> +    private String title;
Todo Entity에서 크기를 30글자로 제한을 두셨는데 요청 받을때도 제한 두는거 어떻게 생각하시나요!
@Min, @Max, @Size 를 이용해서 크기를 제한할 수 있습니다!

2024-09-30 14:27 UTC, cousim46 commented on src/test/java/com/app/todolist/api/todos/TodoControllerTest.java
> +
해당 테스트코드는 컨트롤러 테스트라고 하기에는 애매한거 같습니다!
TodoRequest에 대한 단위 테스트인거 같습니다!

2024-09-30 14:27 UTC, cousim46 commented on src/test/java/com/app/todolist/domain/todos/TodoRepositoryTest.java
해당 테스트코드에서 Todo Entity에 요소들만 검증을 하고 있는거 같습니다.
Todo를 생성한 Member에 대한 값도 추가하는게 어떨가요!

as-is
```java
@DisplayName("회원이 저장한 Todo를 조회할 수 있다.")
    public void createTest() {
        //given
        Todo todo = Todo.create("todo-list", "hello");
        Member member = Member.create("tao@exemple.com", "1234");
        memberRepository.save(member);
        Todo todo = Todo.create(member, "todo-list", "hello");
        todoRepository.save(todo);

        //when
        Todo findTodo = todosRepository.findAll().stream().findAny().orElseThrow();

        //then
        Todo findTodo = todoRepository.findAll().stream().findFirst().orElseThrow();
        Assertions.assertThat(findTodo.getTitle()).isEqualTo(todo.getTitle());
        Assertions.assertThat(findTodo.getContent()).isEqualTo(todo.getContent());
}
```

to-be
```java
@DisplayName("회원이 저장한 Todo를 조회할 수 있다.")
    public void createTest() {
        //given
        Todo todo = Todo.create("todo-list", "hello");
        Member member = Member.create("tao@exemple.com", "1234");
        memberRepository.save(member);
        Todo todo = Todo.create(member, "todo-list", "hello");
        todoRepository.save(todo);

        //when
        Todo findTodo = todosRepository.findAll().stream().findAny().orElseThrow();

        //then
        Todo findTodo = todoRepository.findAll().stream().findFirst().orElseThrow();
        Member findMember = findTodo.getMember();
        Assertions.assertThat(findTodo.getTitle()).isEqualTo(todo.getTitle());
        Assertions.assertThat(findTodo.getContent()).isEqualTo(todo.getContent());
        Assertions.assertThat(member.getEmail()).isEqualTo(findMember.getEmail());
        Assertions.assertThat(member.getPassword()).isEqualTo(findMember.getPassword());
}
```

2024-09-30 14:27 UTC, cousim46 commented on src/test/java/com/app/todolist/api/todos/TodoServiceTest.java
> +class TodoServiceTest {
제가 Repository에 관련된 테스트코드에 대한 리뷰와 동일합니다.
해당 테스트코드에서 Todo 엔티티에 대한 값만 검증하고 있고 그것을 생성한 Member에 대해서는 검증을 안하고 있는거 같습니다!
이것도 같이 추가하시면 좋을거 같습니다!

2024-09-30 14:27 UTC, cousim46 commented on src/test/java/com/app/todolist/api/todos/TodoServiceTest.java
> +    }
DisplayName에 존재하지 않는 회원에 대한 테스트코드라고 명시해주셨는데 `when` 절에서 `1L`이라고 작성해주셨는데
1L이 실패할 확률은 100%가 아니라고 생각합니다. 언제든지 나올 수 있는 값이라고 저는 생각합니다.
그래서 저같은 경우는 1L이 아닌 -1L로 하여 절대 나올 수 없는 값으로 설정합니다!
이 방법에 대해서 어떻게 생각하십니까!

2024-09-30 14:27 UTC, cousim46 commented on src/test/java/com/app/todolist/domain/todos/TodoRepositoryTest.java
>      }
해당 테스트코드와 DisplayName에 작성된 내용과 의미가 좀 다른거같습니다!
DisplayName에는 "회원이 저장한 Todo를 조회할 수 있다" 라고 명시해주셨는데 when절에 "Todo 테이블에 저장된 모든 데이터를 조회 후 하나의 결과만 추출"하는 로직처럼 보입니다!

DisplayName과 의미가 같은 테스트 코드가 될려면 when절에는 아래와 같이 작성하는게 적절하다고 생각합니다!

as-is
```java
//given

//when
 Todo findTodo = todoRepository.findAll().stream().findFirst().orElseThrow();
//then
```

to-be
```java
//given
 Member member = Member.create("tao@exemple.com", "1234");
 Member savedMember =  memberRepository.save(member);

//when
 Todo findTodo = todoRepository.findByMember(savedMember).orElseThrow(예외처리);
//then
```

2024-09-30 14:27 UTC, cousim46 commented on src/test/java/com/app/todolist/api/todos/TodoServiceTest.java
> +    }
해당 테스트 코드를 읽기전  DisplayName으로 테스트코드를 유추룰 하게 된다면 아래와 같이 해석할 수 있을거 같습니다.

Member 생성하는 비즈니스 로직 + Todo를 생성하는 비즈니스 로직

이 테스트 코드는 Todo를 생성하는 비즈니스 로직만 존재해야한다고 생각합니다!

그래서 DisplayName을 아래와 같이 수정하면 어떨까요!?
@DisplayName("회원이 Todo를 생성한다.")

그리고 제 개인 취향이긴 한데 DisplayName에는 ~~ 할 수 있다. 등 가능성이 있다 라는 말로 끝맺음을 하는것보다는 ~~ 다. ~~ 한다. 이렇게 끝맺음하는걸 좋아합니다! (이거는 제 개인 취향입니다!)

2024-10-01 14:47 UTC, o-tao commented on src/main/java/com/app/todolist/api/todos/dto/TodoRequest.java
> +    private String title;
넵 해당내용 확인 후 기존 title 글자 30자리 초과 시 Internal Server Error로 처리 되는것을 확인하였습니다.

```java
    // as-is
    @NotBlank(message = "제목을 입력하세요.")
    private String title;

    // to-be
    @Size(min = 2, max = 30, message = "제목은 2자리 이상, 30자리 이하 입력이 가능합니다.")
    @NotBlank(message = "제목을 입력하세요.")
    private String title;
```

말씀해주신 내용 반영하여 최소 입력값과 최대 입력값을 설정하여 해당내용에 대한 에러 시 BAD_REQUEST 처리 되도록 변경하였습니다!

```json
// error
{
    "code": 400,
    "message": "제목은 2자리 이상, 30자리 이하 입력이 가능합니다."
}
```

2024-10-01 15:49 UTC, o-tao commented on src/test/java/com/app/todolist/domain/todos/TodoRepositoryTest.java
말씀해주신 내용을 토대로 확인해보니 생성된 Todo가 Member가 생성한 Todo가 맞는지에 대한 명확성이 떨어졌던 것 같습니다.
해당내용 반영하여 Todo를 생성한 Member와 동일한지에 대한 내용 추가하였습니다.
짚어주셔서 감사합니다!

2024-10-01 16:27 UTC, o-tao commented on src/test/java/com/app/todolist/api/todos/TodoServiceTest.java
> +class TodoServiceTest {
해당내용 반영하였습니다!

해당 내용에 대한 테스트코드 작성 시 LazyInitializationException에 대한 에러가 발생하였는데 TodoEntity에
```java
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    private Member member;
```
fetch = FetchType.LAZY로 설정된 객체를 세션이 종료된 후에 접근하려고 해 발생한 오류로 확인하였습니다.

해결방법으로
1. default값인 fetch = FetchType.EAGER로 설정하여 즉시로드
2. 해당 테스트코드에 @Transactional 어노테이션을 추가하여 세션유지

이렇게 두가지를 확인하였는데, 개인적으로는 현재로서는 해당 테스트코드에서만 확인된 에러이기때문에 fetch = FetchType.EAGER로 설정하여 전체 코드에 영향을 줄 수도 있는 방법보다는
해당 테스트코드에 @Transactional 어노테이션을 추가하여 테스트 실행시에만 세션을 유지하여 LazyInitializationException에 대한 에러를 피할 수 있도록 하였습니다.

2024-10-01 16:34 UTC, o-tao commented on src/test/java/com/app/todolist/api/todos/TodoServiceTest.java
> +    }
말씀해주신 것처럼 회원이 존재하지 않을 시 발생할 수 있는 에러에 대한 테스트코드에서 해당 회원이 존재 할 확률을 없애 더욱 명확하게 바라볼 수 있다고 생각하여 해당내용 반영하였습니다 감사합니다!

2024-10-01 16:46 UTC, o-tao commented on src/test/java/com/app/todolist/api/todos/TodoServiceTest.java
> +    }
말씀해주신쪽이 더욱 직관적이라고 생각하여 DisplayName 수정하였습니다 감사합니다 :)

2024-10-02 15:31 UTC, o-tao commented on src/test/java/com/app/todolist/api/todos/TodoControllerTest.java
> +
말씀해주신 내용 반영하여 TodoControllerTest -> TodoRequestTest로 변경하였습니다.

TodoRequestTest에 대한 단위 테스트로 변경하며 min, max에 대한 예외처리 테스트코드 내용 추가하였습니다.

Member에 대한 테스트 또한 Todo와 동일하게 ControllerTest -> RequestTest로 변경하며 email 패턴에 대한 테스트코드 내용 추가하였습니다.

테스트 코드 작성 중 Request에 대한 객체를 반복적으로 생성하는 것을 확인하여 @BeforeEach 어노테이션을 사용한 setup 메서드에 추가하여 반복되는 코드를 간소화 하였습니다

```java
// TodoRequestTest 추가 테스트코드 내용

    private Validator validator = null;
    private TodoRequest todoRequest;

    @BeforeEach
    public void setup() {
        validator = Validation.buildDefaultValidatorFactory().getValidator();
        todoRequest = new TodoRequest();
    }

    @Test
    @DisplayName("title을 최소 2자리이상 입력하지않으면 예외가 발생한다.")
    public void minTitleTest() {
        // given
        todoRequest.setTitle("t");

        // when
        Set<ConstraintViolation<TodoRequest>> violations = validator.validate(todoRequest);

        // then
        Assertions.assertThat(violations)
                .extracting(ConstraintViolation::getMessage)
                .contains("제목은 2자리 이상, 30자리 이하 입력이 가능합니다.")
                .hasSize(1);
    }

    @Test
    @DisplayName("title을 최대 30자리 초과 입력 시 예외가 발생한다.")
    public void maxTitleTest() {
        // given
        todoRequest.setTitle("abcdefghijklmnopqrstuvwxyz12345");

        // when
        Set<ConstraintViolation<TodoRequest>> violations = validator.validate(todoRequest);

        // then
        Assertions.assertThat(violations)
                .extracting(ConstraintViolation::getMessage)
                .contains("제목은 2자리 이상, 30자리 이하 입력이 가능합니다.")
                .hasSize(1);
    }

    @Test
    @DisplayName("title을 Size범위 내에 입력 시 예외가 발생하지 않는다.")
    public void sizeSuccessTest() {
        // given
        todoRequest.setTitle("todo title");

        // when
        Set<ConstraintViolation<TodoRequest>> violations = validator.validate(todoRequest);

        // then
        Assertions.assertThat(violations)
                .extracting(ConstraintViolation::getMessage)
                .contains()
                .hasSize(0);
    }
```

```java
// MemberRequestTest 추가 테스트코드 내용

    private Validator validator = null;
    private MemberRequest memberRequest;

    @BeforeEach
    public void setupValidator() {
        validator = Validation.buildDefaultValidatorFactory().getValidator();
        memberRequest = new MemberRequest();
    }

    @Test
    @DisplayName("이메일 형식이 아닐 경우 예외가 발생한다.")
    public void emailPatternTest() {
        // given
        memberRequest.setEmail("tao123");
        memberRequest.setPassword("1234");

        // when
        Set<ConstraintViolation<MemberRequest>> violations = validator.validate(memberRequest);

        // then
        assertThat(violations)
                .extracting(ConstraintViolation::getMessage)
                .contains("이메일 형식이 올바르지 않습니다.")
                .hasSize(1);
    }

    @Test
    @DisplayName("이메일 형식일 경우 예외가 발생하지 않는다.")
    public void emailPatternSuccessTest() {
        // given
        memberRequest.setEmail("tao123@exemple.com");
        memberRequest.setPassword("1234");

        // when
        Set<ConstraintViolation<MemberRequest>> violations = validator.validate(memberRequest);

        // then
        assertThat(violations)
                .extracting(ConstraintViolation::getMessage)
                .contains()
                .hasSize(0);
    }
```

2024-10-02 16:26 UTC, o-tao commented on src/test/java/com/app/todolist/domain/todos/TodoRepositoryTest.java
>      }
회운님이 남겨주신 리뷰 내용 확인하여 확인해 보았는데 말씀해주신 것처럼 DisplayName에 대한 내용의 의미가 불확실했다고 느껴졌습니다.

그래서 DisplayName과 의미가 같도록 예시를 주신것과 같이 테스트 코드를 작성하려고 했으나
```java
//when
 Todo findTodo = todoRepository.findByMember(savedMember).orElseThrow(예외처리);
```

이 부분에서 todoRepository에 findByMember 또는 findByMemberId를 통해 Member에 대해 조회해 오려고 하였는데
Todo Entity에서 해당 내용을 하기 위해서는 TodoRepository에 Member를 조회해오기 위한 쿼리메서드를 생성해야하는데 현재 해당 쿼리메서드를 생성하게 되면 오직 테스트코드에서만 사용하는 상황이 그려졌습니다.

그래서 DisplayName을 좀 더 명확하게 하고 그에 맞는 테스트코드로 수정해보았는데 확인해보시고 의견 남겨주시면 감사하겠습니다!!

```java
    // as-is
    @Test
    @DisplayName("회원이 저장한 Todo를 조회할 수 있다.")
    public void createTest() {
        //given
        Member member = Member.create("tao@exemple.com", "1234");
        memberRepository.save(member);

        Todo todo = Todo.create(member, "todo-list", "hello");
        todoRepository.save(todo);

        //when
        Todo findTodo = todoRepository.findAll().stream().findFirst().orElseThrow();

        //then
        Member findMember = findTodo.getMember();
        Assertions.assertThat(member.getEmail()).isEqualTo(findMember.getEmail());
        Assertions.assertThat(member.getPassword()).isEqualTo(findMember.getPassword());
        Assertions.assertThat(findTodo.getTitle()).isEqualTo(todo.getTitle());
        Assertions.assertThat(findTodo.getContent()).isEqualTo(todo.getContent());

    }

    // to-be
    @Test
    @DisplayName("저장한 모든 Todo를 조회할 수 있다.")
    public void findByAllTest() {
        //given
        Member member = Member.create("tao@exemple.com", "1234");
        memberRepository.save(member);

        Todo todo1 = Todo.create(member, "todo-list", "hello");
        Todo todo2 = Todo.create(member, "todo-list", "hello");
        Todo todo3 = Todo.create(member, "todo-list", "hello");
        todoRepository.save(todo1);
        todoRepository.save(todo2);
        todoRepository.save(todo3);

        //when
        List<Todo> findTodo = todoRepository.findAll();

        //then
        Member findMember = findTodo.getLast().getMember();
        Assertions.assertThat(member.getEmail()).isEqualTo(findMember.getEmail());
        Assertions.assertThat(member.getPassword()).isEqualTo(findMember.getPassword());
        Assertions.assertThat(findTodo).hasSize(3);

    }
```

2024-10-03 08:10 UTC, loadkrnis reviewed
전체적으로 잘하고 계십니다 :)
고생하셨습니다!

2024-10-03 08:10 UTC, loadkrnis commented on src/main/java/com/app/todolist/api/todos/dto/TodoRequest.java
> +
요청 클래스의 memberId 값에 대해서는 유효성 체크가 빠진 것 같습니다! 아래 처럼 체크되면 좋을 것 같은데 어떻게 생각하실까요?

```java
@NotNull(message = "회원 ID를 입력하세요.")
@Positive(message = "회원 ID는 양수여야 합니다.")
private Long memberId;
```

추가적으로 content 값도 유효성 체크가 추가되면 좋을 것 같습니다.

2024-10-03 08:10 UTC, loadkrnis commented on src/main/java/com/app/todolist/domain/todos/Todo.java
>      private String content;
혹시 이 content는 왜 length도 지정되어 있지 않고 nullable할까요?
이와 관련해서 [이 글](https://jojoldu.tistory.com/718)을 읽어보시면 좋을 것 같습니다.

length가 지정되지 않아서 varchar255로 지정될 것 같은데요. 컨텐트의 길이가 255로 제한되어 있나요? 
=> 그렇다면 request 클래스에서 길이 255 유효성 체크가 추가되어야할 것 같습니다. 

만약 content 길이가 제한되어 있지 않다면 [mysql TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT 차이점](https://dung-beetle.tistory.com/72)을 공부해보시고 아래처럼 적용해보시면 좋을 것 같습니다.

```java
@Column(columnDefinition = "TEXT", nullable = false)
private String content;
```

2024-10-03 08:10 UTC, loadkrnis commented on src/main/java/com/app/todolist/exception/ErrorCode.java
> +    NOT_EXISTED_EMAIL(HttpStatus.BAD_REQUEST, "회원이 존재하지 않습니다.");
enum은 `NOT_EXISTED_EMAIL`인데 `회원이 존재하지 않습니다.` 메시지를 가지고 있네용?? 

메시지가 뭔가 상이되는 느낌입니다 ㅎㅎ

2024-10-03 10:41 UTC, o-tao commented on src/main/java/com/app/todolist/api/todos/dto/TodoRequest.java
> +
말씀해주신 내용 확인 후 기존 memberId가 null 값으로 요청 될 시 Internal Server Error로 처리 되는것을 확인하였습니다.

말씀해주신 내용 반영하여 null, 양수가 아닌 수가 요청 될 경우 BAD_REQUEST 처리 되도록 변경하였습니다.
```json
// null error
{
    "code": 400,
    "message": "회원 ID를 입력하세요."
}

// 양수 error
{
    "code": 400,
    "message": "회원 ID는 양수여야 합니다."
}
```

민규님이 남겨주신 리뷰를 반영하던 중 memberId에 문자가 들어 올 경우 JSON parse error가 발생, 이에대한 에러처리가 안되어 있는것을 확인하였습니다.
```json
// BAD_REQUEST ex
{
    "memberId": "a",
    "title": "todo title",
    "content": "todo content"
}
```
이 부분은 ExceptionHandler로 전역처리를 해야할 것으로 보여 해당 에러사항에 대해서는 별도의 이슈로 (#24) 수정하도록 하겠습니다!

2024-10-04 12:42 UTC, cousim46 reviewed
제가 처음에 남긴 리뷰에 대해서 정말 잘 반영해주셨네요! 감사합니다!
추가적으로 보이는게 있어서 리뷰를 작성하였습니다!
이해가 안되는 부분 또는 의아한 부분은 편하게 말씀해주세요 :)

고생하셨습니다!

2024-10-04 12:42 UTC, cousim46 commented on src/main/java/com/app/todolist/api/todos/dto/TodoResponse.java
> +                .status(Status.TODO.name())
제가 아래 작성한 Json 값은 README.md에 작성해주신 ResponseBody입니다.
```json
{
  "id": 1,
  "title": "todo title",
  "content": "todo content",
  "status": "TODO",
  "createdAt": "2024-09-14 14:35:33",
  "updatedAt": "2024-09-14 14:35:33",
  "member": {
    "id": 1,
    "email": "tao@example.com"
  }
}
```

여기서 Status의 값을 "TODO"로 응답을 해주고 있습니다.

그럼 여기서 name() 메서드를 호출안하셔도 될거같습니다!
name() 메서드를 호출안하고 하는방법은 아래와 같습니다.

as-is
```java
@Builder
@Getter
public class TodoResponse {

    private Long id;
    private String title;
    private String content;
    private String status;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdAt;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updatedAt;

    private TodoMemberInfo member;

    public static TodoResponse of(Todo todo) {
        return TodoResponse.builder()
                .id(todo.getId())
                .title(todo.getTitle())
                .content(todo.getContent())
                .status(Status.TODO.name())
                .createdAt(todo.getCreatedAt())
                .updatedAt(todo.getUpdatedAt())
                .member(new TodoMemberInfo(todo.getMember().getId(), todo.getMember().getEmail()))
                .build();
    }
 //생략
```

to-be
```java
@Builder
@Getter
public class TodoResponse {

    private Long id;
    private String title;
    private String content;
    private Status status;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createdAt;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updatedAt;

    private TodoMemberInfo member;

    public static TodoResponse of(Todo todo) {
        return TodoResponse.builder()
                .id(todo.getId())
                .title(todo.getTitle())
                .content(todo.getContent())
                .status(Status.TODO)
                .createdAt(todo.getCreatedAt())
                .updatedAt(todo.getUpdatedAt())
                .member(new TodoMemberInfo(todo.getMember().getId(), todo.getMember().getEmail()))
                .build();
    }
 //생략
```

데이터타입을 String -> Enum Class 값으로 변경하면 될거같습니다.

2024-10-04 12:42 UTC, cousim46 commented on src/test/java/com/app/todolist/api/members/dto/MemberRequestTest.java
> +    }
DisplayName을 읽고 테스트 코드를 봤는데 DisplayNamer과 테스트 코드의 의미가 100% 동일한거 같지는 않습니다.
이유는 테스트 코드에서는 Email을 null 또는 값을 채워서 테스트를 하고 있는데 DisplayName과 메서드 명을 봤을때는 
테이블의 기본키의 id를 명시한다고 저는 느꼈습니다. 그래서 저는 아래와 같이 DisplayName을 작성할거 같습니다.
as-is
```
@DisplayName("아이디를 입력하지 않을 경우 예외가 발생한다.")
```

to-be
```java
@DisplayName("이메일을 입력하지 않을 경우 예외가 발생한다.")
```

as-is
```java
@DisplayName("아이디를 입력할 경우 예외가 발생하지 않는다.")
```

to-be
```java
@DisplayName("이메일을 입력할 경우 예외가 발생하지 않는다.")
```

2024-10-04 12:42 UTC, cousim46 commented on src/test/java/com/app/todolist/api/todos/dto/TodoRequestTest.java
> +
테스트를 위해서 하나씩 값을 채우는 방식도 좋지만 아래와 같은 방법도 있습니다! 참고하시면 좋을거 같아서 리뷰 달았습니다.
as-is
```java
 todoRequest.setTitle("abcdefghijklmnopqrstuvwxyz12345");
```

to-be
```java
 todoRequest.setTitle("a".repeat(31));
```

2024-10-04 17:15 UTC, o-tao commented on src/main/java/com/app/todolist/domain/todos/Todo.java
>      private String content;
저같은 경우 TodoList 사용 시 기본적으로 리스트에서 title이 보여지고 해당 title을 선택했을 때 상세 조회에서 content까지 보여주는 것을 생각해 title의 경우 사용자가 Todo를 작성할 때 반드시 입력되어야 하는 값이지만 content는 null값이 들어오더라도 무관하다고 생각하였습니다

민규님이 언급해주신 nullable에 대한 참고글을 토대로 학습하였는데
nullable할 경우에 코드내에서 항상 null에 대한 체크가 이루어져야하며, null값을 위해 쿼리의 추가적인 조건의 필요함 등 다방면에서 복잡도를 증가시킬 수 있음을 알게 되었습니다.
null값에 대한 명확한 목적이 없는 경우 불필요한 복잡도를 증가시킬 수 있다고 생각이 들어 민규님이 언급해주신 내용에 대해 반영하였습니다. 감사합니다!

content 길이제한에 대해 참고해주신 글도 잘 읽어보았습니다. 
저같은 경우 단순히 JPA에서 길이설정을 하지 않을경우 varchar(255)로 지정될 것을 생각하고 길이제한을 두지 않았습니다.
코드를 보았을때 혼동스러울 수 있다고 생각이 들어 명시적으로 길이제한(length=250)을 두고 Request 클래스또한 길이제한에 대한 유효성 체크를 추가하였습니다.

```java
// as-is

// Todo Entity, Request
private String content;

// to-be

// Todo Entity
@Column(nullable = false, length = 250)
private String content;

// TodoRequest
@Size(max = 250, message = "내용은 250자리 이하 입력이 가능합니다.")
@NotNull(message = "내용을 입력하세요.")
private String content;
```

길이 제한에 대해 한번 더 짚어주셔서 감사합니다 덕분에 그 차이를 좀 더 자세히 알게되었습니다
말씀해주신 내용에 대해 기억해두고 필요시 말씀해주신 것을 토대로 적용해보도록하겠습니다!

2024-10-04 17:20 UTC, o-tao commented on src/main/java/com/app/todolist/exception/ErrorCode.java
> +    NOT_EXISTED_EMAIL(HttpStatus.BAD_REQUEST, "회원이 존재하지 않습니다.");
말씀해주신 내용 MEMBER_NOT_FOUND로 변경하였습니다!!

2024-10-04 17:27 UTC, o-tao commented on src/main/java/com/app/todolist/api/todos/dto/TodoResponse.java
> +                .status(Status.TODO.name())
말씀해주신 내용 반영하였습니다!
코드 작성할때 왜 String타입을 고집했을까요ㅎㅎ.. 회운님이 짚어준 내용으로 반영하니 더욱 깔끔해진거같습니다 감사합니다 :)

2024-10-04 17:31 UTC, o-tao commented on src/test/java/com/app/todolist/api/members/dto/MemberRequestTest.java
> +    }
테스트 코드 작성 시 email = 사용자 아이디 라고 혼자서 생각하며 작성했던거 같습니다
회운님이 말씀해주신 내용 확인해보니 충분히 기본키의 id와 혼동이 있을거라고 생각이 드네요

말씀해주신 내용 반영하였습니다 감사합니다! :)

2024-10-04 17:43 UTC, o-tao commented on src/test/java/com/app/todolist/api/todos/dto/TodoRequestTest.java
> +
이런 세세한 부분까지 체크해주셔서 정말 감사합니다 덕분에 더 좋은 코드를 짤 수 있을거같습니다 ㅎㅎ
해당내용 반영하며 Request 유효성체크에 대한 부분으로 인해 변경사항까지 모두 수정하였습니다!!

2024-10-07 09:30 UTC, cousim46 approved these changes
리뷰 반영 정말 잘해주셨네요!
고생하셨습니다 :)

2024-10-09 10:03 UTC, merged